### ISSUE TITLE
databricksx12.hls package is missing from the pip installation

### ISSUE THREAD

**Issue by kenatlogix** [databricks-industry-solutions/x12-edi-parser#13]
Did the pip installation as guided:
pip install git+https://github.com/databricks-industry-solutions/x12-edi-parser

But then for the import modules as below:
from databricksx12.hls import *
, it errored out:
ModuleNotFoundError: No module named 'databricksx12.hls'

Found that setup.py misses the package.  A workaround I made, copied the missing folder, .../databrickx12/hls, from the source code repo and manually located in the installation path. 

The setup.py code should be modified as below:

from setuptools import setup, **find_packages**
from io import open
from os import path
import sys

this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, "README.md"), encoding="utf-8") as f:
    LONG_DESCRIPTION = f.read()

setup(
    name="databricksx12",
    version="0.0.1",
...
...
    ],
    #packages=['databricksx12'],
    **packages=find_packages()**
    #py_modules=['databricksx12']
)

**Comment by zavoraad** [comment]
Hi @kenatlogix , sorry for the late reply didn't have notifications on. 

Setup.py is modified on hotfix13 branch to include databricksx12.hls as a package.  Can you confirm you can import after installing from this branch? 

```bash
pip install git+https://github.com/databricks-industry-solutions/x12-edi-parser.git@hotfix13
```

```python
from databricksx12.hls import *
```

**Comment by kenatlogix** [comment]
Hi @zavoraad , 
Thanks for the info and the fix.  I have verified it. !
