### ISSUE TITLE
Other diagnosis are a repeating elements in a single segment

### ISSUE THREAD

**Issue by zavoraad** [databricks-industry-solutions/x12-edi-parser#15]
https://github.com/databricks-industry-solutions/x12-edi-parser/blob/9d693528b20e29a37f978ffb90841ec31c570630/databricksx12/hls/identities.py#L72

See ABF example here 
https://datainsight.health/edi/claims/institutional-837i/institutional-claim/

**Comment by ankushgovil** [comment]
You can update the other_dx_cds as:
self.other_dx_cds = ",".join([s.element(index, 1) for s in hi_segments for index in range(1, 13) if s.element(index, 0) == "ABF"])

**Comment by zavoraad** [comment]
Thanks @ankushgovil for this insight. Is it possible that there may be more than 1 segment of ABF as well? I've updated code in a hotfix branch to align with what you shared, plus if there is multiple ABF segments too. 

https://github.com/databricks-industry-solutions/x12-edi-parser/blob/hotfix-15-thru-20-issues/databricksx12/hls/identities.py#L72-L74

**Comment by zavoraad** [comment]
Fixed and tested here https://github.com/databricks-industry-solutions/x12-edi-parser/blob/hotfix-15-thru-20-issues/tests/test_issues.py#L43-L47
