### ISSUE TITLE
DTP segment can be multiple

### ISSUE THREAD

**Issue by ankushgovil** [databricks-industry-solutions/x12-edi-parser#24]
Current code only fetches the first DTP segment in 2300 loop. DTP can come as multiple values:
For ex: 096(Discharge), 
434(Statement),
435(Admission)
![Screenshot 2024-11-16 at 2 18 58 AM](https://github.com/user-attachments/assets/53fd6ebe-85e9-4e6a-a4bf-4bce464dca7f)

**Comment by zavoraad** [comment]
Thanks @ankushgovil. I saw that was the case in the 835s and handled it like [this](https://github.com/databricks-industry-solutions/x12-edi-parser/blob/main/databricksx12/hls/claim.py#L395). I'll plan to do the same thing above for the 2300 to capture all the DTP values
